### ISSUE TITLE
Display benchmark results in a table format

### ISSUE THREAD

**Issue by BenceKovari** [sigstat/sigstat#6]
See [sample.txt](https://github.com/sigstat/sigstat/files/3012668/sample.txt) for sample data

**Comment by hargitomi97** [comment]
Couldn't solve it with our current table generation. 
Complex tables like this probably requires a library to use, e.g, [Tabulator](http://tabulator.info/).

**Comment by BenceKovari** [comment]
Give a more modern look to the table. Tooltips should appear on mouse over similarly to this: http://community.dj-extensions.com/uploads/editor/q7/ybckx9n2mjxf.jpg

**Comment by hargitomi97** [comment]
Table with additional tooltip information has been implemented. Table is fully generated from javascript and works with the data format provided in _sample.txt_.

**Comment by BenceKovari** [comment]
The table looks nice :) Please add the following modifications:
- only a singlé error rate (AER) should be displayed in a cell
- results should be in %, with two decimal places. eg.: 32,50%, 12,45%
- column titles should have vertical orientation
- tooltip on cells should include FAR, FRR, AER, and column and row title data
- there should be an option to move the mouse over the text of the tooltip
- hyperlinks in the tooltip should be navigable
- add tow summary columns in the sample dataset
  - Average
  - Average Core
- add support for columnType: summary setting in the sample data format
- upload sample dataset to the site

**Comment by hargitomi97** [comment]
All of them done. Refactoring the code in the coming days.
